title: "ChatWorkMentionTaskを作った #railsdm #rdm2018A"
author: "sue445"
#theme: "sky"

meta_properties:
  og:locale: "ja_JP"
  og:type: "website"
  og:title: "ChatWorkMentionTaskを作った #railsdm #rdm2018A"
  og:description: "Rails Developers Meetup 2018: Day 2の発表資料です"
  og:url: "https://sue445.github.io/rails-developers-meetup-2018/#/"
  og:image: "https://sue445.github.io/rails-developers-meetup-2018/images/cover.png"

meta_names:
  twitter:card: "Summary"
  twitter:site: "@sue445"
  twitter:creator: "@sue445"
  twitter:title: "ChatWorkMentionTaskを作った #railsdm #rdm2018A"
  twitter:description: "Rails Developers Meetup 2018: Day 2の発表資料です"
  twitter:image: "https://sue445.github.io/rails-developers-meetup-2018/images/cover.png"
